nombre = input('¿Cómo te llamas?')
edad = input('¿Cuántos años tienes?')
trabajo = input('¿En qué trabajas?')
videojuego = input('¿Cuál es tu videojuego favorito?')
lenguaje = input('¿Cuál es tu lenguaje de programación favorito?')

print('\n -----PRESENTACION----- \n')
print(f"Hola, mi nombre es {nombre}")
print(f'Tengo {edad} años')
print(f'Trabajo como {trabajo}')
print(f'Mi juego favorito es {videojuego}')
print(f'Mi lenguaje de programacion favorito es {lenguaje}')
print(f'\n-----Bienvenido a al Proyecto Renacer-Backend-----\n')
print(f"Mi meta es convertirme en Backend Developer especializado en Bases de Datos. 🚀")